### ISSUE TITLE
Gameboy Color testing

### ISSUE THREAD

**Issue by ghost** [calc84maniac/tiboyce#140] opened 2021-09-12 19:06 UTC
So I got bored and started trying to use gbc games on it, so it tried Super Mario Deluxe and when i load it, it shows this game is not designed for Game Boy, so I would like to request you guys to work on gbc support too, thanks bye!

**Comment by Eeems** [comment] 2021-09-12 22:36
Duplicate of #54

**Closed** 2021-12-07 07:22 UTC
Labels: duplicate
