### ISSUE TITLE
Problem of menu

### ISSUE THREAD

**Issue by Majoran145** [calc84maniac/tiboyce#107] opened 2019-12-01 11:09 UTC
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
**TI-Boy CE version:** 0.1.3 (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
Hello, I would like to play the game "Mystic Quest". The game is playable, but there is a huge problem : it is impossible to open the inventory, and so it is impossible to solve the first enigma... Could you tell me if the problem was from my version of TI-Boy CE, from the ROM or from the ROM conversion ? Thanks a lot !

**Comment by ndye** [comment] 2019-12-02 17:59
Just to clarify you do understand the button mappings for the emulator? Additionally try using a different ROM and see if it works better. If that doesn't help then yes it is probably a bug with the emulator. Also what calc version are you using?

**Comment by Majoran145** [comment] 2019-12-02 21:29
No, I can open the menu and choose the secondary menu (between objects, equipment and magic), but after that, there is only the cursor which appears. Except that, I tried to open the menu on a real emulator, and it worked...
I played with a TI-83 Premium CE (5.4.0.0034) and the TI-Boy CE Alpha 0.1.3 version....

**Comment by calc84maniac** [comment] 2021-09-24 21:41
Duplicate of #69

**Closed by calc84maniac** 2021-09-24 21:41 UTC
Labels: bug, duplicate, accuracy
