### ISSUE TITLE
ROM converter "allows" gba roms but doesn't do anything with it

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#32] opened 2018-07-22 23:29 UTC

**Comment by LAX18** [comment] 2018-07-23 00:57
Perhaps a hint at future functionality?

***LAX18 Runs

**Comment by mateoconlechuga** [comment] 2018-07-23 01:03
gba will never happen

**Comment by jcgter777** [comment] 2018-07-23 01:49
I wish it will though :P

**Comment by LAX18** [comment] 2018-07-23 02:33
Yea... I knew GBA was never going to happen. It was one of the things @calc84maniac made explicitly clear... just wishfull thinking...

**Comment by calc84maniac** [comment] 2018-07-23 02:42
What do you mean by "doesn't do anything"? Is this another case of the web converter not giving an error message for files that are too large?

I'm not going to arbitrarily disallow any kind of ROMs by analyzing them. A ROM is just a bunch of data, if you put the wrong thing in then a Game Boy won't run it.

**Comment by calc84maniac** [comment] 2018-07-23 02:56
I'm going to go ahead and mark this as a duplicate of the real issue, #33.

**Closed by calc84maniac** 2018-07-23 02:56 UTC
