### ISSUE TITLE
Error: Ran an invalid Game Boy opcode at 00FAEF

### ISSUE THREAD

**Issue by IntentionalGD** [calc84maniac/tiboyce#175] opened 2022-09-19 01:40 UTC
(See my next comment)

**Comment by calc84maniac** [comment] 2022-09-19 01:49
Could you give some more information about this? What game were you running, and when did it happen? (In other words, fill out the blanks in the issue form, please.)

**Comment by IntentionalGD** [comment] 2022-09-19 01:51
What is wrong: error message instead of the effect describe in the glitch link below
Version: Alpha v0.2.1


Steps to reproduce:
1.Run Pokémon Silver
2.Perform this glitch: https://m.youtube.com/watch?v=CiDi5nb-uoc
(also I am fully aware I am performing glitches so if this is the sole reason for the issue, that’s fine, but if it isn’t I want to make sure it is the issue is reported)
3. Get taken to an error screen as soon as the coin case item is used
4. The error is the title


Again, the error output is the title. Done on calculator and not emulator of calculator.

**Comment by IntentionalGD** [comment] 2022-09-19 01:52
Sorry, I have never used this feature on GitHub before and think I pressed comment before starting the actual response.

**Comment by calc84maniac** [comment] 2022-09-19 02:43
No problem, thanks for the info. Makes sense that it's related to a glitch because that can cause unusual situations, haha. If possible, could you share a save file with the conditions for doing the glitch already prepared?

**Comment by IntentionalGD** [comment] 2022-09-19 03:16
[SilverGlitch.sav.zip](https://github.com/calc84maniac/tiboyce/files/9595967/SilverGlitch.sav.zip)
Here. If you want me to test anything or need any more files, don't hesitate to let me know. Also, I appreciate the timely response.

**Comment by IntentionalGD** [comment] 2022-09-19 03:16
[MartsSAV.8xv.zip](https://github.com/calc84maniac/tiboyce/files/9595969/MartsSAV.8xv.zip)
I just realized that was in .sav and not .8xv

**Comment by calc84maniac** [comment] 2022-10-22 06:22
I'm checking out this issue now, and I'm trying to perform the glitch on another emulator (BGB) first so I know how it works. Have you managed to get it to work on another emulator?

I did notice the names of your PC boxes are slightly different than the tutorial video, but even after fixing that, I can't successfully execute the glitch. I do manage to crash the game, sometimes even executing an invalid opcode, but I don't get the behavior described in the tutorial.

Looking more into the glitch, apparently there's a good bit of RNG for whether the freshly-caught Pokémon (aka the ["slide Pokémon"](https://glitchcity.wiki/Coin_Case_glitches#Slide_Pok.C3.A9mon)) will work for it. I'm concerned that perhaps the one you caught wasn't sufficient, and that's why this error is popping up.

**Comment by calc84maniac** [comment] 2022-12-05 00:13
Closing this until there's a replication on the current release, with a glitch setup that's been confirmed to work on accurate emulators.

**Closed by calc84maniac** 2022-12-05 00:13 UTC
Labels: bug, accuracy
