### ISSUE TITLE
calculator white screens

### ISSUE THREAD

**Issue by Rerarted** [calc84maniac/tiboyce#88] opened 2019-08-21 20:59 UTC
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (5.4.0)
**TI-Boy CE version:** … (0.1.2a)
The calculator whitescreens after i start any rom and i have push the rest button on the back but it doesn't stop

**Comment by jacobly0** [comment] 2019-08-21 23:23
Probably duplicate of #85, since tiboy doesn't work on the new revision M hardware which also doesn't always reset correctly.  To hard reset your calc hold the reset button for 3-5 seconds.

**Comment by Rerarted** [comment] 2019-08-22 01:00
but is there a way i can get it to run the roms

**Comment by adriweb** [comment] 2019-08-22 01:07
No, since it's incompatible with the hardware revision of your calculator (look at the back of your calc, to the right of the serial number if it shows L-0519M it's not compatible).
You'll have to wait until TI-Boy CE is fixed to support those versions.

**Comment by Rerarted** [comment] 2019-08-22 01:47
when do you plan on fixing TI-Boy CE

**Comment by jcgter777** [comment] 2019-08-22 02:42
It should be fixed in a month or so. According to another duplicate thread.

**Comment by adriweb** [comment] 2019-08-22 04:48
@calc84maniac answered [here](https://github.com/calc84maniac/tiboyce/issues/87#issuecomment-522809393)

**Closed by adriweb** 2019-08-22 04:48 UTC
