### ISSUE TITLE
White screen when running pkmn blue

### ISSUE THREAD

**Issue by drewp2196** [calc84maniac/tiboyce#141] opened 2021-09-16 20:06 UTC
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … 5.4.0.0034
**TI-Boy CE version:** … 0.1.2
**Describe your issue:**  
So my friend got the program on her calculator and it worked fine. I transferred the tiboyce pgrm from her calculator, along with a bunch of other games/files. When I first opened the program, it told me that I needed more ram. I went into my files and deleted everything I knew I could spare. I also did garbage collect and reset the RAM. When I opened it again, I got a continuous white screen that I couldn't leave. I pressed the reset button on the back and I could use my calc again. when I tried to run pkmn blue, the same thing happened. Sometimes it will tell me that I need more RAM but when I cleared the RAM it would give me the white screen. I am currently trying to kill my calculator so it clears the RAM. These are all the files on my calculator that I think are relevant. Please tell me if there are others I am missing.
EzDcSave
FileIOC
FONTLIBC
GRAPHX
KEYPADC
Libload
OREFILE
OiramPk
OIRAMS
Oiramsv
OiramT
PokeB
PokeBR00
PokeBR01
PokeBR02
PokeBR03
PokeBR04
PokeBR05
PokeBR06
PokeBR07
PokeBR08
PokeBSt1
PokeBSt3
PokeBStA
TIBoyCfg
TiBoyDat
TiboySkn
Ticsfile

**Comment by calc84maniac** [comment] 2021-09-16 20:09
This is a duplicate of issue #136, would you mind trying out the file I uploaded there and see if it fixes your issue? Also, to get out of the white screen state you *should* be able to quick exit the emulator with ON and use 2nd+ON to turn the calculator off and back on.

**Comment by drewp2196** [comment] 2021-09-16 21:05
I don't have access to ti - connect; I got this from a friends calculator, but i can try to get it. The only way to exit the program once it goes white is to press the reset button. It only goes white if I have enough ram to run the program

**Comment by drewp2196** [comment] 2021-09-16 21:08
I also thought this would be different because that was with the python calculator and my programs didn't work with that.

**Comment by calc84maniac** [comment] 2021-09-16 21:19
Oh, sorry I made that assumption. I also didn't notice you were using version 0.1.2. I believe this is an issue with your calculator being too new for that version, you should download the 0.1.3 release and see if that works.

**Comment by FreshSamurai** [comment] 2021-12-11 00:26
Yes, you should download the new release. That worked for me, I had the same problem.

**Comment by teddblue** [comment] 2022-03-24 21:37
i suppose im late to the party, but https://ticalc.link/ can be used to send files to and from the calculator

**Comment by calc84maniac** [comment] 2022-03-24 21:48
Closing this issue because it seems to have been related to an old release.

**Closed by calc84maniac** 2022-03-24 21:48 UTC
