### ISSUE TITLE
Support for Correct Colors on Gameboy Color Games

### ISSUE THREAD

**Issue by joshoea** [calc84maniac/tiboyce#143] opened 2021-09-20 04:26 UTC
**Is your feature request related to a problem? Please describe.**
Gameboy color games do not have proper color palettes. i.e. super mario land 2 + pokemon gold/silver

**Describe the solution you'd like**
Support for gbc color palettes. ,

**Comment by Eeems** [comment] 2021-09-20 14:51
Duplicate of #54

**Closed** 2021-12-07 07:27 UTC
Labels: duplicate
