### ISSUE TITLE
Error: Ran an invalid Game Boy opcode at 0016D

### ISSUE THREAD

**Issue by John32145653** [calc84maniac/tiboyce#211] opened 2024-05-11 01:27 UTC
GameBoy  "Dr. Rin ni Kiitemite! - Koi no Rin Fuusui (Japan)" 

Caculator  Ti-84 plus ce python

**Comment by calc84maniac** [comment] 2024-05-11 03:03
Seems like this is an issue caused by not treating the STOP instruction as 2 bytes, since this game uses a non-standard STOP encoding. It's fixed now on the dev branch, and should be included in the next release.

**Comment by John32145653** [comment] 2024-05-11 21:00
I have no clue where to start. The 2 code you provided what are you supposed to do with them?

**Comment by Eeems** [comment] 2024-05-11 21:14
> I have no clue where to start. The 2 code you provided what are you supposed to do with them?

I think you missed this part:

> It's fixed now on the dev branch, and should be included in the next release.

You don't need to do anything. Just wait for the next release and it'll be fixed.

**Closed** 2024-06-05 05:14 UTC
Labels: bug, accuracy
