### ISSUE TITLE
Glitchy display on some calculator revisions

### ISSUE THREAD

**Issue by Mathusalle** [calc84maniac/tiboyce#178] opened 2022-11-11 01:25 UTC
Ok, for weeks I have been messing around with Ti boy because the screen didn't look right...I have talked to tiny hacker about the problem and he said that it was broken and he tried it himself and he had the same problems that I had. The problem is 
that the right part of the screen is glitched and when you run rom or game, the screen is white with some parts of the right side being glitched as well. I don't know what to do, I tried both new versions from github and calc84maniacs site and both of them don't work on either CEmu and my physical.

**Comment by TIny-Hacker** [comment] 2022-11-11 01:29
It seems the issue is happening with version 0.2.1, it works fine on 0.2.0 for both of us.

**Comment by adriweb** [comment] 2022-11-11 01:48
You should add details. Which game/ROM, which calculator hardware revision, etc.

**Comment by Mathusalle** [comment] 2022-11-11 01:51
Pokemon blue, red,and yellow. Also for Mario land, monopoly, and Shaq. And some other roms.

**Comment by Eeems** [comment] 2022-11-11 01:52
Pictures of the issue would also be useful.

**Comment by calc84maniac** [comment] 2022-11-11 02:18
It's 100% expected that this version doesn't work on CEmu, that's a problem with CEmu and not TI-Boy. But does the exact same thing happen on a real calculator? As mentioned, the hardware revision from the back of the calculator and a photo of the issue would be helpful.

**Comment by Mathusalle** [comment] 2022-11-11 02:26
Just so yall know IT has been used on both CEmu and a Physical, I will supply photos when ready.

**Comment by Mathusalle** [comment] 2022-11-11 02:28
![Ti boy test 1,000](https://user-images.githubusercontent.com/108593199/201249288-842ccb2c-d96a-429e-9ec5-8658e040f89e.png)

**Comment by Mathusalle** [comment] 2022-11-11 02:33
The second photo was taken on a real calc. The first on CEmu.

**Comment by calc84maniac** [comment] 2022-11-11 02:51
And what's the date code and revision of the calculator? It's the part on the back that looks like L-0716C (just an example from one of my own calculators).

I can try to put together a quick build that undoes some of my changes to the SPI interface (since I think that's the most likely culprit) and see if it helps at all.

**Comment by calc84maniac** [comment] 2022-11-11 03:02
Here's a shot in the dark at an improvement, can you see if this works? [TIBoyDat-issue-178.zip](https://github.com/calc84maniac/tiboyce/files/9986168/TIBoyDat-issue-178.zip)

**Comment by Mathusalle** [comment] 2022-11-11 14:50
The version of my calculator is 5.3 and the revision of the calc is L-02222W

**Comment by calc84maniac** [comment] 2022-11-11 16:36
Thanks. Also, since I won't have time for most of today to make more builds, here's a quick CEmu build (tries to be as compatible with CEmu as possible, though fullscreen mode will look weird in CEmu regardless). If the other build I gave doesn't work on a physical calculator, try this one as well: 
[TIBoyDat-issue-178-CEmu.zip](https://github.com/calc84maniac/tiboyce/files/9991695/TIBoyDat-issue-178-CEmu.zip)

**Comment by TIny-Hacker** [comment] 2022-11-12 13:17
After further investigation it seems that TI-Boy CE 0.2.1 is at least working on my calculator now, I'm not sure what the issue was earlier.

**Comment by Mathusalle** [comment] 2022-11-14 23:32
I think version 0.2.1 might work for physical calculators, and most likely won't work for the emulator, even if it's 0.3.  Also, the zip for the TIboyDat-issue works fine for the physical but not the emulator(as expected)

**Comment by calc84maniac** [comment] 2022-11-15 01:59
Nice, so that build fixes the issue for you? I'll definitely put in a fix for this in the next release, then.

**Comment by Mathusalle** [comment] 2022-11-18 01:51
It works except their is a split screen(when I run a rom), is that supposed to happen or is it a feature? Looks cool anyways...

**Comment by calc84maniac** [comment] 2022-11-18 02:05
On which? The CEmu build looks like that on CEmu, but is it happening on a real calculator too? Though turning off fullscreen mode works on CEmu, at least.

**Comment by calc84maniac** [comment] 2022-11-18 21:27
Ah, so it's only occasional? Are you using the first or second build on the real calc? I'm concerned that maybe I'm still sending SPI commands too quickly so some of them aren't getting through. The second build (the CEmu one) should still run on a real calc, but it sends SPI commands more slowly than the first one.

**Comment by Mathusalle** [comment] 2022-11-18 23:48
I'm using both, but the first build kinda works(on my real calc, not CEmu), but the second does(it also creates a split screen but it can be fixed manually for both calculators.)

**Comment by calc84maniac** [comment] 2022-12-04 23:40
Should be fixed in v0.3.0 since I put in that change. Closing the issue for now.

**Closed by calc84maniac** 2022-12-04 23:40 UTC
Labels: bug
