### ISSUE TITLE
Occasionally when starting up pokemon gold, I get a runtime error. 

### ISSUE THREAD

**Issue by thegamingnobody** [calc84maniac/tiboyce#155] opened 2021-12-08 11:14 UTC
Version 0.2.0
Opening tiboyce itself isn't a problem, but sometimes when starting up pokemon gold I get a runtime error. When I click on pokemon gold again after that, the game starts up as normal but the rom is just restarted. Not sure if this also happens with other games/roms.

**Comment by calc84maniac** [comment] 2021-12-08 15:56
This sounds like some kind of problem with loading the auto save state. Are you additionally having problems with the in-game save data when this happens, or does it still load properly? Are you in a particular place in the game (as in the place where you exited the game to auto-save) where this happens?

**Comment by thegamingnobody** [comment] 2021-12-08 18:27
It seems like the error only pops up when loading the auto save state while in the overworld. In my very quick testing run, I never got the error during battle, only in the overworld.

**Comment by calc84maniac** [comment] 2021-12-09 02:59
I'm having a hard time reproducing this problem. It might be a bit of a hassle, but could you try to get a bad auto save state transferred to your PC?

Basically exit the emulator in an area where you've been having the problem, and transfer the `StA` and `SAV` files to your PC. Then if you manage to get a runtime error when loading the emulator up again, then you'll already have those files on your PC. Then you can zip up those two files and upload them here.

**Comment by thegamingnobody** [comment] 2021-12-09 13:39
I haven't been able to transfer the files to my PC yet, that'll have to be for tonight or tomorrow, but here are some quick notes:
(sorry in advance for spelling errors, my spelling check isn't set on English somehow and is screaming at me right now lol)
- any menu (pokédex, party of pokémon etc.) seems to be fine as well.
- I'll add a quick save file too just to be sure, because that's how I'm saving my progress rn
- maybe it has something to do with the time/day-night mechanic? I haven't tested out any other games yet, but since the problem only occurs on the overworld it my be something like that. I recall the time jumping around in previous versions if Tiboyce, idk.
- I've been following the project since basically the very start and I have to say, the new colo(u)r palette is one of the best additions yet IMO, really amazing for the immersion.

**Comment by calc84maniac** [comment] 2021-12-09 15:20
I actually had the same thought that it may have something to do with the time mechanic. I took a closer look at the state loading code around the RTC and I have an idea of something that may be causing code corruption. Could you try using this TIBoyDat file and see if it fixes your problems? [TIBoyDat-issue-155.zip](https://github.com/calc84maniac/tiboyce/files/7686269/TIBoyDat-issue-155.zip)

**Comment by calc84maniac** [comment] 2021-12-09 15:41
Also incidentally, the time jumping on load is an intentional feature, since it uses the clock on the calculator to track time when not playing. The way it's emulated, it'll even jump forward to the current time immediately when loading a save state (which I guess is unusual from an actual system's perspective, but Pokémon seems to handle it fine)

**Comment by thegamingnobody** [comment] 2021-12-09 15:52
Yeah the issue seems fixed on first glance! I'll test out some things later but my first 2 or 3 tries were without any errors, thanks! Even though I used the clock feature to get to nighttime etc., I thought it was unintentional, since I found out you can manipulate how much the clock jumps by changing your timezone. (I don't remember exactly how it worked, but I remember there being a connection.)

**Comment by thegamingnobody** [comment] 2021-12-09 15:53
Before you close the issue, I just want to thank you from the bottom om my heart for this project, I can't even explain how much I love it, thanks you.

**Comment by calc84maniac** [comment] 2021-12-09 16:44
Yeah, the timezone is relative to the calculator's clock, so changing it without also changing the calculator clock would have an effect on the game. 

I'll leave the issue open a little longer so you can make sure the problem is gone (and so anyone else having the issue can see it), but I'll see about preparing a minor release soon if it's all good.

**Closed** 2021-12-10 04:04 UTC
Labels: bug
