### ISSUE TITLE
Ability to change rom location

### ISSUE THREAD

**Issue by minireaper01** [calc84maniac/tiboyce#198] opened 2023-09-15 23:24 UTC
I'm trying to use a USB drive so i can actually get more use out of TIBoyCE and the app runs fine while in a USB stick but I cant launch roms on the same stick.

I'd like just an option to have TIBoyCE access roms from the same folder it is installed in.

There might also possibly a way to select a separate folder as well, for organization.

**Comment by calc84maniac** [comment] 2023-09-16 01:08
Duplicate of #130

**Closed by calc84maniac** 2023-09-16 01:08 UTC
